// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7vJL5hsybEdRKWPPElzojNOrYTQh97qQ',
    appId: '1:1041193245380:web:8714a118bae0d469c80791',
    messagingSenderId: '1041193245380',
    projectId: 'aura-ed792',
    authDomain: 'aura-ed792.firebaseapp.com',
    storageBucket: 'aura-ed792.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoyyvns-Hg-wAZQaMmJyI3SXSm7xdjwUw',
    appId: '1:1041193245380:android:bc92fc14de905abec80791',
    messagingSenderId: '1041193245380',
    projectId: 'aura-ed792',
    storageBucket: 'aura-ed792.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChUhc7d9LQ3PmmytjiDQ-CmPNAQYX0fG0',
    appId: '1:1041193245380:ios:3ea86dd6c9124333c80791',
    messagingSenderId: '1041193245380',
    projectId: 'aura-ed792',
    storageBucket: 'aura-ed792.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChUhc7d9LQ3PmmytjiDQ-CmPNAQYX0fG0',
    appId: '1:1041193245380:ios:3ea86dd6c9124333c80791',
    messagingSenderId: '1041193245380',
    projectId: 'aura-ed792',
    storageBucket: 'aura-ed792.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7vJL5hsybEdRKWPPElzojNOrYTQh97qQ',
    appId: '1:1041193245380:web:f6654dc42542882bc80791',
    messagingSenderId: '1041193245380',
    projectId: 'aura-ed792',
    authDomain: 'aura-ed792.firebaseapp.com',
    storageBucket: 'aura-ed792.firebasestorage.app',
  );
}
